name: "MLOps workflow - Analyze Code"

on:
  push:
    paths:
      # trigger op deze bestanden
      - 'workdir_model_training/**.py'
      - 'workdir_model_training/**.txt'
      - 'workdir_model_training/data/BankNote_Authentication.csv'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'app/**.py'
  # maak handmatig starten van de workflow ook mogelijk
  workflow_dispatch:

jobs:
  # analiseer de python source op vulnerabilities
  analyze_code:
    # voorkom parallel jobs
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2