name: IaC

on:
  # maak handmatig starten van de workflow ook mogelijk
  workflow_dispatch:
env:
  AZURE_RESOURCEGROUP_NAME: 'rg-containerml'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      loginServer: ${{ steps.build.outputs.loginServer }}

    steps:
       # checkout de code naar de Github workspace
       - name: 'Checkout GitHub Action'
         uses: actions/checkout@v3
       
       # log in bij Azure Cloud
       - name: 'Login via Azure CLI'
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

       # maak de Azure resource group
       - name: 'Deploy Azure Container Registry'
         uses: azure/arm-deploy@v1
         with:
           subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
           resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
           template: ./deploy/main.bicep
      
