name: Retrain Model

on:
  workflow_dispatch:
  push:
    paths:
      - 'workdir_model_training/data/BankNote_Authentication.csv'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Retrain the model
        run: python workdir_model_training/logistische-regressie.py
      - name: Copy the file from the runner to the repo
        run: |
          git config --global user.email "marcel@siebes.nl"
          git config --global user.name "MarcelSiebes"
          git add workdir_model_training/logistische-regressie.pkl
          git commit -m "new trained model"
          git push
          
