name: "MLOps workflow - Train Model"

on:
  # start deze workflow nadat de code door CodeQL is geanalyseerd
  workflow_run:
    workflows: ["MLOps workflow - Analyze Python Code"]
    types: [completed]
  # maak handmatig starten van de workflow ook mogelijk
  workflow_dispatch:

jobs:
  # train het model en push de pickle file naar de github repository
  train_and_push_model:
    name: 'Train the logistic regression model'
    runs-on: ubuntu-latest

    steps:
      # checkout de code naar de Github workspace
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # gebruik python 9; hier is de code mee getest
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # installeer de modules vermeld in de requirements
      - name: 'Install dependencies'
        run: pip install -r workdir_model_training/requirements.txt

      # train het model
      - name: 'Train the model'
        run: python workdir_model_training/logistische-regressie.py

     # push de pickle file vanuit de runner naar de githun repository
      - name: 'Push the file pickle file'
        run: |
          git config --global user.email "marcel@siebes.nl"
          git config --global user.name "MarcelSiebes"
          git add workdir_model_training/logistische-regressie.pkl
          git commit -m "new trained model"
          git push
